# Logging settings
logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: INFO
        boot: INFO
        ai: INFO
      hibernate: INFO
    com:
      github: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
  logback:
    rollingpolicy:
      max-file-size: ${LOGGING_FILE_MAX_SIZE:300MB}
      max-history: ${LOGGING_FILE_MAX_HISTORY:3}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: spring-ai-lang-chain4j

# LangChain4j settings
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.openai.com/v1
      api-key: demo
      model-name: gpt-4o-mini
      temperature: 0.7
      max-tokens: 2000
      timeout: 60s
      log-requests: true
      log-responses: true

# BigModel settings
bigmodel:
  api-key: demo